module.exports = {
  places: {
    BERCARIO_MISSIONARIO: "BERCARIO_MISSIONARIO",
    PEQUENOS_MISSIONARIOS: "PEQUENOS_MISSIONARIOS",
    DESBRAVADORES_MISSIONARIOS: "DESBRAVADORES_MISSIONARIOS",
    GTEEN: "GTEEN",
    CASA: "CASA",
    BANHEIRO: "BANHEIRO",
  },
};
